language: cpp
compiler:
  - gcc
  - clang
env:
  - SUBTARGET=arcade
  - SUBTARGET=mess
script:
  - if [ $CC == 'clang' ];
    then make -j2 linux_x64_clang;
    else make -j2;
    fi
sudo: required
before_install:
  - sudo add-apt-repository ppa:zoogie/sdl2-snapshots -y
  - sudo add-apt-repository ppa:shahar-evron/qt-backports -y
  - sudo apt-get update -qq
  - sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libasound2-dev libqt4-dev libqt4-dev-bin
