language: cpp
compiler:
  - gcc
  - clang
env:
  - SUBTARGET=arcade MAME=mamearcade64
  - SUBTARGET=mess   MAME=mess64
script:
  - if [ $CC == 'clang' ];
    then make -j2 linux_x64_clang && ./$MAME -validate;
    else make -j2 OPTIMIZE=0      && ./$MAME -validate;
    fi
sudo: required
before_install:
  - sudo add-apt-repository ppa:zoogie/sdl2-snapshots -y
  - sudo add-apt-repository ppa:ubuntu-sdk-team/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libasound2-dev qtbase5-dev qt5-default qttools5-dev-tools
notifications:
  email: false
