name: CI (macOS)

on:
  push:
    paths:
    - '.github/**'
    - '3rdparty/**'
    - 'scripts/**'
    - 'src/**'
    - 'COPYING'
    - 'makefile'
  pull_request:
    paths:
    - '.github/**'
    - '3rdparty/**'
    - 'scripts/**'
    - 'src/**'
    - 'COPYING'
    - 'makefile'

jobs:
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: brew install python3 sdl2 cmake
      - name: Build
        run: |
          cmake . -DTOOLS=ON
          make -j2
      - name: Validate
        run: ./mame -validate
      - uses: actions/upload-artifact@master
        with:
          name: mame-macos-${{ github.sha }}
          path: mame
